name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull Docker image
        run: docker pull wlsf82/gitlab-ce:latest
      - name: Run Docker container
        run: docker run --publish 80:80 --hostname localhost wlsf82/gitlab-ce
      - name: Cypress run
        uses: cypress-io/github-action@v6